<?php

/**
 * @file
 * Stringoverride install.
 */

/**
 * Implements hook_uninstall().
 */
function stringoverrides_uninstall() {
  // Remove all stored string replacements.
  $or = db_or()
    ->condition('name', 'locale_custom_strings_%', 'LIKE')
    ->condition('name', 'locale_custom_disabled_strings_%', 'LIKE');
  db_delete('variable')->condition($or)->execute();
}

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function stringoverrides_update_7000() { }
